name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  create-repo:
    name: create-repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform init
        run: terraform init

      - name: Terraform fmt
        run: terraform fmt

      - name: Terraform plan
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN_ORG}}
        run: terraform plan -var="github_token=${{secrets.TOKEN_ORG}}"
      
      - name: Terraform apply
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
        run: terraform apply -var="github_token=${{secrets.TOKEN_ORG}}" -auto-approve
